### ISSUE TITLE
It's bad. 

### ISSUE THREAD

**Issue by 22seegerb** [novialriptide/LagCheck#1]
Idk but the more I use this plugin the more I realize "yknow what, it's kinda bad". I've thought this for years but only recently with the release of minecraft 1.17 do I really recognize the shortcomings in this plugin.

1: Spigot is bad
2: The word "spigot" is silly
3: I don't like you in particular
4: My antivirius deleted the file after I flagged it as a virus
5: It's bad.
5: It could use some bug fixing
4: It's not good.

**Comment by novialriptide** [comment]
https://c.tenor.com/ZMgayECBpN8AAAAC/ur-mom-dance.gif
